-- PotentialDS creator CRM foundation.
-- Run before 002_email_outreach.sql and 003_traffic_monitoring.sql.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.creator_lists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  description text,
  color text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.saved_creators (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  list_id uuid not null references public.creator_lists(id) on delete cascade,
  influencer_id uuid not null references public.influencers(id) on delete cascade,
  source text not null default 'search'
    check (source in ('search', 'recommendation', 'import', 'manual')),
  created_at timestamptz not null default now(),
  unique (list_id, influencer_id)
);

create table if not exists public.creator_relationships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  influencer_id uuid not null references public.influencers(id) on delete cascade,
  status text not null default 'to_contact' check (
    status in ('to_contact', 'sent', 'opened', 'clicked', 'replied',
      'negotiating', 'partnered', 'rejected', 'paused')
  ),
  contact_name text,
  contact_email text,
  contact_phone text,
  owner_name text,
  quoted_price numeric(14, 2) check (quoted_price is null or quoted_price >= 0),
  quoted_currency text not null default 'USD' check (char_length(quoted_currency) = 3),
  custom_tags text[] not null default '{}',
  last_contacted_at timestamptz,
  next_follow_up_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, influencer_id)
);

create table if not exists public.creator_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  relationship_id uuid not null references public.creator_relationships(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.creator_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  relationship_id uuid references public.creator_relationships(id) on delete cascade,
  influencer_id uuid not null references public.influencers(id) on delete cascade,
  activity_type text not null check (
    activity_type in ('saved', 'removed', 'note_added', 'status_changed',
      'email_sent', 'email_opened', 'email_clicked', 'email_replied',
      'follow_up_scheduled', 'imported', 'exported')
  ),
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.creator_import_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  list_id uuid references public.creator_lists(id) on delete set null,
  file_name text not null,
  file_type text not null check (file_type in ('csv', 'xlsx')),
  status text not null default 'pending' check (
    status in ('pending', 'validating', 'processing', 'completed', 'failed', 'cancelled')
  ),
  total_rows integer not null default 0,
  imported_rows integer not null default 0,
  skipped_rows integer not null default 0,
  failed_rows integer not null default 0,
  field_mapping jsonb not null default '{}'::jsonb,
  error_summary jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.creator_recommendation_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_influencer_id uuid not null references public.influencers(id) on delete cascade,
  recommended_influencer_id uuid not null references public.influencers(id) on delete cascade,
  action text not null check (action in ('shown', 'opened', 'saved', 'dismissed')),
  algorithm_version text not null default 'rules-v1',
  created_at timestamptz not null default now()
);

create index if not exists creator_lists_user_idx
  on public.creator_lists (user_id, updated_at desc);
create index if not exists saved_creators_user_idx
  on public.saved_creators (user_id, created_at desc);
create index if not exists saved_creators_influencer_idx
  on public.saved_creators (influencer_id);
create index if not exists creator_relationships_pipeline_idx
  on public.creator_relationships (user_id, status, updated_at desc);
create index if not exists creator_relationships_follow_up_idx
  on public.creator_relationships (user_id, next_follow_up_at)
  where next_follow_up_at is not null;
create index if not exists creator_notes_relationship_idx
  on public.creator_notes (relationship_id, created_at desc);
create index if not exists creator_activities_relationship_idx
  on public.creator_activities (relationship_id, occurred_at desc);
create index if not exists creator_import_jobs_user_idx
  on public.creator_import_jobs (user_id, created_at desc);

drop trigger if exists creator_lists_set_updated_at on public.creator_lists;
create trigger creator_lists_set_updated_at before update on public.creator_lists
for each row execute function public.set_updated_at();
drop trigger if exists creator_relationships_set_updated_at on public.creator_relationships;
create trigger creator_relationships_set_updated_at before update on public.creator_relationships
for each row execute function public.set_updated_at();
drop trigger if exists creator_notes_set_updated_at on public.creator_notes;
create trigger creator_notes_set_updated_at before update on public.creator_notes
for each row execute function public.set_updated_at();

alter table public.creator_lists enable row level security;
alter table public.saved_creators enable row level security;
alter table public.creator_relationships enable row level security;
alter table public.creator_notes enable row level security;
alter table public.creator_activities enable row level security;
alter table public.creator_import_jobs enable row level security;
alter table public.creator_recommendation_feedback enable row level security;

drop policy if exists creator_lists_owner on public.creator_lists;
create policy creator_lists_owner on public.creator_lists for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists saved_creators_owner on public.saved_creators;
create policy saved_creators_owner on public.saved_creators for all to authenticated
using (auth.uid() = user_id and exists (
  select 1 from public.creator_lists l where l.id = list_id and l.user_id = auth.uid()
)) with check (auth.uid() = user_id and exists (
  select 1 from public.creator_lists l where l.id = list_id and l.user_id = auth.uid()
));

drop policy if exists creator_relationships_owner on public.creator_relationships;
create policy creator_relationships_owner on public.creator_relationships for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists creator_notes_owner on public.creator_notes;
create policy creator_notes_owner on public.creator_notes for all to authenticated
using (auth.uid() = user_id and exists (
  select 1 from public.creator_relationships r
  where r.id = relationship_id and r.user_id = auth.uid()
)) with check (auth.uid() = user_id and exists (
  select 1 from public.creator_relationships r
  where r.id = relationship_id and r.user_id = auth.uid()
));

drop policy if exists creator_activities_owner on public.creator_activities;
create policy creator_activities_owner on public.creator_activities for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists creator_import_jobs_owner on public.creator_import_jobs;
create policy creator_import_jobs_owner on public.creator_import_jobs for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists creator_recommendation_feedback_owner on public.creator_recommendation_feedback;
create policy creator_recommendation_feedback_owner
on public.creator_recommendation_feedback for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
