-- Outreach email and engagement tracking.
-- Messages/events are written by trusted server routes, not the browser.

create table if not exists public.email_templates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  subject_template text not null check (char_length(subject_template) between 1 and 300),
  html_template text not null,
  text_template text,
  variables text[] not null default '{}',
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_campaigns (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  list_id uuid references public.creator_lists(id) on delete set null,
  template_id uuid references public.email_templates(id) on delete set null,
  name text not null,
  status text not null default 'draft' check (
    status in ('draft', 'scheduled', 'sending', 'paused', 'completed', 'cancelled')
  ),
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  daily_send_limit integer not null default 50 check (daily_send_limit between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  campaign_id uuid references public.email_campaigns(id) on delete set null,
  template_id uuid references public.email_templates(id) on delete set null,
  relationship_id uuid references public.creator_relationships(id) on delete set null,
  influencer_id uuid references public.influencers(id) on delete set null,
  recipient_email text not null,
  recipient_name text,
  sender_email text,
  sender_name text,
  subject text not null,
  html_body text not null,
  text_body text,
  provider text,
  provider_message_id text,
  status text not null default 'queued' check (
    status in ('queued', 'sending', 'sent', 'delivered', 'opened', 'clicked',
      'replied', 'bounced', 'complained', 'unsubscribed', 'failed', 'cancelled')
  ),
  tracking_token uuid not null default gen_random_uuid() unique,
  sent_at timestamptz,
  delivered_at timestamptz,
  first_opened_at timestamptz,
  last_opened_at timestamptz,
  first_clicked_at timestamptz,
  replied_at timestamptz,
  bounced_at timestamptz,
  open_count integer not null default 0,
  click_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.email_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (
    event_type in ('queued', 'sent', 'delivered', 'opened', 'clicked',
      'replied', 'bounced', 'complained', 'unsubscribed', 'failed')
  ),
  provider text,
  provider_event_id text,
  event_source text not null default 'provider' check (
    event_source in ('provider', 'tracking_pixel', 'tracked_link', 'mailbox_sync', 'manual')
  ),
  is_machine_generated boolean,
  ip_hash text,
  user_agent_hash text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.email_links (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.email_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_url text not null,
  click_count integer not null default 0,
  first_clicked_at timestamptz,
  last_clicked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.email_unsubscribes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  reason text,
  source_message_id uuid references public.email_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (user_id, email)
);

create index if not exists email_templates_user_idx
  on public.email_templates (user_id, updated_at desc);
create index if not exists email_campaigns_user_idx
  on public.email_campaigns (user_id, status, created_at desc);
create index if not exists email_messages_user_idx
  on public.email_messages (user_id, created_at desc);
create index if not exists email_messages_campaign_idx
  on public.email_messages (campaign_id, status);
create index if not exists email_events_message_idx
  on public.email_events (message_id, occurred_at desc);
create index if not exists email_events_user_idx
  on public.email_events (user_id, event_type, occurred_at desc);
create index if not exists email_links_message_idx
  on public.email_links (message_id);
create unique index if not exists email_events_provider_unique
  on public.email_events (provider, provider_event_id)
  where provider_event_id is not null;

drop trigger if exists email_templates_set_updated_at on public.email_templates;
create trigger email_templates_set_updated_at before update on public.email_templates
for each row execute function public.set_updated_at();
drop trigger if exists email_campaigns_set_updated_at on public.email_campaigns;
create trigger email_campaigns_set_updated_at before update on public.email_campaigns
for each row execute function public.set_updated_at();
drop trigger if exists email_messages_set_updated_at on public.email_messages;
create trigger email_messages_set_updated_at before update on public.email_messages
for each row execute function public.set_updated_at();

alter table public.email_templates enable row level security;
alter table public.email_campaigns enable row level security;
alter table public.email_messages enable row level security;
alter table public.email_events enable row level security;
alter table public.email_links enable row level security;
alter table public.email_unsubscribes enable row level security;

drop policy if exists email_templates_owner on public.email_templates;
create policy email_templates_owner on public.email_templates for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists email_campaigns_owner on public.email_campaigns;
create policy email_campaigns_owner on public.email_campaigns for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists email_messages_owner_read on public.email_messages;
create policy email_messages_owner_read on public.email_messages for select to authenticated
using (auth.uid() = user_id);
drop policy if exists email_events_owner_read on public.email_events;
create policy email_events_owner_read on public.email_events for select to authenticated
using (auth.uid() = user_id);
drop policy if exists email_links_owner_read on public.email_links;
create policy email_links_owner_read on public.email_links for select to authenticated
using (auth.uid() = user_id);
drop policy if exists email_unsubscribes_owner_read on public.email_unsubscribes;
create policy email_unsubscribes_owner_read on public.email_unsubscribes for select to authenticated
using (auth.uid() = user_id);

-- No browser write policies exist for messages/events/unsubscribes. The server
-- uses the service role so users cannot forge sends, opens, clicks or replies.
