-- Product analytics and bot-risk monitoring.
-- Store hashes, never raw IP addresses or full user-agent strings.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id_hash text,
  session_id uuid,
  event_name text not null,
  entry_path text,
  page_path text not null,
  referrer_domain text,
  traffic_source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  country_code text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (char_length(event_name) between 1 and 100),
  check (country_code is null or char_length(country_code) = 2)
);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  ip_hash text,
  fingerprint_hash text,
  route text not null,
  method text,
  status_code integer,
  user_agent_class text,
  event_type text not null check (
    event_type in ('rate_limit', 'high_frequency', 'enumeration', 'bulk_export',
      'auth_abuse', 'suspicious_agent', 'known_bot', 'blocked_request')
  ),
  risk_score smallint not null default 0 check (risk_score between 0 and 100),
  reasons text[] not null default '{}',
  request_count integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.security_rate_limits (
  bucket_key_hash text not null,
  route_group text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 0,
  blocked_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (bucket_key_hash, route_group, window_started_at)
);

create table if not exists public.security_allowlist (
  id uuid primary key default gen_random_uuid(),
  match_type text not null check (match_type in ('ip_hash', 'fingerprint_hash', 'user_id')),
  match_value text not null,
  reason text not null,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (match_type, match_value)
);

create or replace function public.increment_security_rate_limit(
  p_bucket_key_hash text,
  p_route_group text,
  p_window_started_at timestamptz
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  insert into public.security_rate_limits (
    bucket_key_hash,
    route_group,
    window_started_at,
    request_count,
    updated_at
  )
  values (p_bucket_key_hash, p_route_group, p_window_started_at, 1, now())
  on conflict (bucket_key_hash, route_group, window_started_at)
  do update set
    request_count = public.security_rate_limits.request_count + 1,
    updated_at = now()
  returning request_count into next_count;

  return next_count;
end;
$$;

revoke all on function public.increment_security_rate_limit(text, text, timestamptz) from public;
revoke all on function public.increment_security_rate_limit(text, text, timestamptz) from anon;
revoke all on function public.increment_security_rate_limit(text, text, timestamptz) from authenticated;
grant execute on function public.increment_security_rate_limit(text, text, timestamptz) to service_role;

create index if not exists analytics_events_time_idx
  on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_entry_idx
  on public.analytics_events (entry_path, occurred_at desc);
create index if not exists analytics_events_source_idx
  on public.analytics_events (traffic_source, utm_source, occurred_at desc);
create index if not exists analytics_events_name_idx
  on public.analytics_events (event_name, occurred_at desc);
create index if not exists security_events_time_idx
  on public.security_events (occurred_at desc);
create index if not exists security_events_risk_idx
  on public.security_events (risk_score desc, occurred_at desc);
create index if not exists security_events_ip_idx
  on public.security_events (ip_hash, occurred_at desc)
  where ip_hash is not null;
create index if not exists security_events_route_idx
  on public.security_events (route, event_type, occurred_at desc);

alter table public.analytics_events enable row level security;
alter table public.security_events enable row level security;
alter table public.security_rate_limits enable row level security;
alter table public.security_allowlist enable row level security;

-- No client policies. Ingestion and dashboards use trusted server routes.
-- This prevents visitors from reading traffic or security telemetry.

create or replace function public.purge_expired_telemetry()
returns void language plpgsql security definer set search_path = public as $$
begin
  delete from public.analytics_events
  where occurred_at < now() - interval '90 days';

  delete from public.security_events
  where occurred_at < now() - interval '30 days';

  delete from public.security_rate_limits
  where window_started_at < now() - interval '2 days';

  delete from public.security_allowlist
  where expires_at is not null and expires_at < now();
end;
$$;
